### ISSUE TITLE
🚀 Roadmap

### ISSUE THREAD

**Issue by hasansezertasan** [hasansezertasan/FastUI-Admin#5]
## Description

This is a tentative roadmap, I will update it as things evolve. Some things might be discarded, others might be added later.

## Roadmap

TL;DR: Flask Admin and Flask AppBuilder are the main inspiration for all the features to be included in FastUI-Admin.

- [ ] Master Layout: FastUI is not a template engine, so there are no common patterns to create pages. We might need a `Master` class to be used as `layout.html`. There is a simple example for this at [fastui-tutorials](https://github.com/hasansezertasan/fastui-tutorials/) repository.
- [ ] Decide on a Framework between [FastAPI](https://github.com/tiangolo/fastapi), [Starlette](https://github.com/encode/starlette/), and [Litestar](https://github.com/litestar-org/litestar).
- [ ] Custom Views: All major Administrative Interface tools have this feature, no details are needed.
- [ ] Default Index View:
- [ ] Navbar Structure
- [ ] Menu Structure
- [ ] Profile Menu Structure
- [ ] Model View for SQLAlchemy

## Note

This issue is just to keep anyone interested updated.
